schema_version = 1
flow_name = "quadratic_demo_tune"
run_id = "20251020_221501"
[residual]
tuning = true
[extra]
spec_file = "quadratic_flow"
tuning_mode = "gap_dial"
target_gap = 0.1
adaptation_rate = 0.1
