from typing import Protocol, Dict
import jax.numpy as jnp

class Manifold(Protocol):
    def exp(self, x: jnp.ndarray, v: jnp.ndarray) -> jnp.ndarray: ...
    def log(self, x: jnp.ndarray, y: jnp.ndarray) -> jnp.ndarray: ...
    def metric(self, x: jnp.ndarray, v: jnp.ndarray, w: jnp.ndarray) -> jnp.ndarray: ...
    def proj_tangent(self, x: jnp.ndarray, v: jnp.ndarray) -> jnp.ndarray: ...
    def retract(self, x: jnp.ndarray, v: jnp.ndarray) -> jnp.ndarray: ...
    def transport(self, x: jnp.ndarray, v: jnp.ndarray, w: jnp.ndarray) -> jnp.ndarray: ...
