name: CI (Python cached)

on:
  push:
    branches: [ main, dev, test ]
    paths-ignore:
      - 'archive/**'
      - 'background/**'
      - 'Design/**'
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main, dev, test ]
    paths-ignore:
      - 'archive/**'
      - 'background/**'
      - 'Design/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'PYTHON_VERSION_PLACEHOLDER'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests (quick lane)
        env:
          PYTEST_ADDOPTS: "--maxfail=1 -q"
        run: |
          pytest -q -m "not experiments and not tuning and not integration and not fda" -k "not parameter_search"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            outputs/test-results.xml
            logs/pytest_debug.log
          if-no-files-found: ignore
